<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Bisca TAES_px-6 space-y-4</name>
   <tag></tag>
   <elementGuidId>c5fab755-4f3a-433a-89c8-9fae33ac9f4b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.px-6.space-y-4</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c106961e-aa59-4668-8189-41e6f39e72aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-slot</name>
      <type>Main</type>
      <value>card-content</value>
      <webElementGuid>43cf94ef-0ddd-4619-8b82-0a01c9f12767</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>px-6 space-y-4</value>
      <webElementGuid>3cf5538f-fb39-4365-aec1-434f2e8650d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Email  Password Email ou password inválida. Log In  Sign Up </value>
      <webElementGuid>0861ebb8-ea73-4d45-9804-54d4693116b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;min-h-screen bg-slate-100 flex items-center justify-center p-4&quot;]/div[@class=&quot;bg-card text-card-foreground flex flex-col gap-6 rounded-xl border py-6 shadow-sm w-full max-w-md&quot;]/div[@class=&quot;px-6 space-y-4&quot;]</value>
      <webElementGuid>5e2f2ddc-275f-4385-bed0-e2ab5fdb2af2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div[2]</value>
      <webElementGuid>4a834673-d416-4bf4-a50a-16e9ede69f9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]</value>
      <webElementGuid>a4e0ee19-39b3-4d8f-8909-ded6025a46cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = ' Email  Password Email ou password inválida. Log In  Sign Up ' or . = ' Email  Password Email ou password inválida. Log In  Sign Up ')]</value>
      <webElementGuid>ffa96204-0f34-4e47-9e01-24bd9a4cb428</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
