<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_0_reka-dropdown-menu-trigger-v-4</name>
   <tag></tag>
   <elementGuidId>504a669c-6cc8-45b8-8f17-b45f4168f4a1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='reka-dropdown-menu-trigger-v-4']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#reka-dropdown-menu-trigger-v-4</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c09e7105-9c3c-4f3b-a829-d6721a8ee8c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-slot</name>
      <type>Main</type>
      <value>dropdown-menu-trigger</value>
      <webElementGuid>2a65a752-7357-44b3-8d85-d06673286c1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>focus:outline-none flex items-center gap-3 group</value>
      <webElementGuid>b8807765-eb35-4671-8e2b-8fc61ff19181</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>reka-dropdown-menu-trigger-v-4</value>
      <webElementGuid>031902cd-eb7a-44a6-8e79-3e533fae41f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c3bca8b2-6d66-4f5f-bdfa-d587b59e2308</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>menu</value>
      <webElementGuid>50075d8c-7ddc-421e-9311-d81286231305</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>65d8798d-6c38-45c9-8076-99cfa739f7a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-state</name>
      <type>Main</type>
      <value>closed</value>
      <webElementGuid>055e1727-660b-4c8b-864c-eab0d71bb9db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>user1</value>
      <webElementGuid>7053f4f5-1367-4e20-a1f8-a6f9c759789f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;reka-dropdown-menu-trigger-v-4&quot;)</value>
      <webElementGuid>e06b8a8a-f8c1-42fc-954b-1031c474ac76</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='reka-dropdown-menu-trigger-v-4']</value>
      <webElementGuid>55ad0fe5-11b1-4c77-a50d-6c3f6f7d6a31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/nav/div/div[2]/button</value>
      <webElementGuid>7b8b9c41-e236-468c-aeb3-c60c2ec306b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Scoreboards'])[1]/following::button[1]</value>
      <webElementGuid>f87d7637-e5eb-45f6-844b-679d8c8c89ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>6961404d-ce91-425e-a17f-2611be8d5495</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'reka-dropdown-menu-trigger-v-4' and @type = 'button' and (text() = 'user1' or . = 'user1')]</value>
      <webElementGuid>74f4ef77-9da8-4a99-a660-1b507ddbdd76</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
