<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Start a practice game_px-5 py-2 bg-e_67c576</name>
   <tag></tag>
   <elementGuidId>24d513be-c0b1-423c-91be-6556925f58f3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div/div/div[2]/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1391997c-f44e-41b7-9199-90a4def9ccfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>px-5 py-2 bg-emerald-600 hover:bg-emerald-700 text-white rounded-xl font-semibold</value>
      <webElementGuid>fbcdc83c-52c3-43c5-a79c-2db780d88af8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Confirm</value>
      <webElementGuid>1f25654b-201b-46b0-baad-b255c48c753e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;min-h-screen bg-gradient-to-b from-emerald-10 to-emerald-100 flex flex-col font-sans select-none&quot;]/div[@class=&quot;fixed inset-0 flex items-center justify-center bg-black/40 backdrop-blur-sm&quot;]/div[@class=&quot;bg-white p-8 rounded-2xl shadow-xl w-96 text-center border border-emerald-200&quot;]/div[@class=&quot;flex gap-4 justify-center&quot;]/button[@class=&quot;px-5 py-2 bg-emerald-600 hover:bg-emerald-700 text-white rounded-xl font-semibold&quot;]</value>
      <webElementGuid>48bfb96b-0dae-4eb7-a9be-3fc8a43f441b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div/div[2]/button</value>
      <webElementGuid>6d33a4b1-1be2-4c20-ba22-9dde61b1112a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Start a practice game'])[1]/following::button[1]</value>
      <webElementGuid>4072a0cf-7305-4bca-a13a-8bc35a86d371</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/preceding::button[1]</value>
      <webElementGuid>82890c67-d7b4-4cb0-8500-7c10ed9c29c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Confirm']/parent::*</value>
      <webElementGuid>17d1e6c3-5b28-44e0-97e7-c4ed42ae639f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[2]/button</value>
      <webElementGuid>bd67e6f9-ae93-4364-9f95-146c69fddb6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Confirm' or . = 'Confirm')]</value>
      <webElementGuid>27bfa8fc-08bb-4467-b9ea-b5662fc6cb97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button</value>
      <webElementGuid>9e670435-29f5-4a2f-b97b-e180ac75181b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
