<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_1</name>
   <tag></tag>
   <elementGuidId>42772682-c918-4cd7-ae14-a0b2a956e783</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[(text() = 'ERROR: Insufficient balance' or . = 'ERROR: Insufficient balance')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e2c63e08-3b37-4131-acea-732f7cd4617c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ERROR: Insufficient balance</value>
      <webElementGuid>5fa93783-4521-4c14-ba5d-13d53eb19e7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/li[1]/div[2]/div[1]</value>
      <webElementGuid>28a8da2c-ab50-4ffd-9e28-c95cf2b16f4b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'ERROR: Insufficient balance' or . = 'ERROR: Insufficient balance')]</value>
      <webElementGuid>2a98281a-d0ad-471f-a595-547779e78984</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
