<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Orus_aspect-square size-full object-cover</name>
   <tag></tag>
   <elementGuidId>0282c75e-70f6-4148-877d-b82136ca98dd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='reka-dropdown-menu-trigger-v-5']/span[2]/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.aspect-square.size-full.object-cover</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>cedff57f-2024-4d6a-bda4-e105c330e217</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>70a15aa0-bab2-40f2-bf08-b36805288479</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://api.dicebear.com/7.x/avataaars/svg?seed=Orus</value>
      <webElementGuid>aa0db1d5-8a5d-48c8-a81e-a12e528979da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-slot</name>
      <type>Main</type>
      <value>avatar-image</value>
      <webElementGuid>f061dabc-111c-4405-a8b2-455c126b1be0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>aspect-square size-full object-cover</value>
      <webElementGuid>bf250eef-2070-4c3e-9878-f1a2e2a583d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;reka-dropdown-menu-trigger-v-5&quot;)/span[@class=&quot;relative flex size-8 shrink-0 overflow-hidden rounded-full cursor-pointer bg-slate-100 group-hover:ring-2 group-hover:ring-slate-200 transition&quot;]/img[@class=&quot;aspect-square size-full object-cover&quot;]</value>
      <webElementGuid>6f4469f1-2768-4eea-b419-aa213e5e179d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='reka-dropdown-menu-trigger-v-5']/span[2]/img</value>
      <webElementGuid>837fc391-7ae4-4c20-b3dd-e885c4abd8a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://api.dicebear.com/7.x/avataaars/svg?seed=Orus')]</value>
      <webElementGuid>c1666c38-0e91-4105-9aeb-40b8a6cd651b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>9f0e2ca9-15f9-4918-b91e-d5e9b37defc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://api.dicebear.com/7.x/avataaars/svg?seed=Orus']</value>
      <webElementGuid>70bb0632-9ee7-4265-ba24-c9d786a816ff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
