<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Trump_card-img_8</name>
   <tag></tag>
   <elementGuidId>41dc00a4-74c2-46b2-8b88-285a3263b779</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div[3]/div/div[9]/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>bb8f35f7-d52d-4f9f-b58a-bbb85c439814</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/src/assets/cards/o3.png</value>
      <webElementGuid>96dd4077-2650-4156-9827-2016aa842ef0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>carta</value>
      <webElementGuid>7fd29bf1-5c7c-44e1-b2de-78a8e3db59e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>card-img</value>
      <webElementGuid>ce267691-a82b-47df-bac9-13688cd47d26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;game-board flex flex-col items-center justify-between min-h-screen bg-green-700 p-4&quot;]/div[@class=&quot;player-hand flex justify-center mb-8&quot;]/div[@class=&quot;player-hand w-28 h-40&quot;]/div[@class=&quot;card-container&quot;]/div[@class=&quot;card&quot;]/img[@class=&quot;card-img&quot;]</value>
      <webElementGuid>8d0e6c72-5222-446f-a6cf-039096e92ad9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[3]/div/div[9]/div/img</value>
      <webElementGuid>1ff31f39-de56-4d64-9c52-8ffde714f9e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='carta'])[20]</value>
      <webElementGuid>d3130ca1-9200-4362-8f47-29751b97c948</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/img</value>
      <webElementGuid>4697264e-e2cb-4032-806a-9f9d0dafcff2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/src/assets/cards/o3.png' and @alt = 'carta']</value>
      <webElementGuid>031fab15-e104-474e-a370-fcf6b3dd1113</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
