<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>avatarFromUserCollection</name>
   <tag></tag>
   <elementGuidId>4830e713-8551-4877-81ad-4204f7a8c603</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.w-full.aspect-square.rounded-full.bg-white.shadow-sm</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//div[@id='app']/div/div[3]/div[2]/div[2]/div/div/img)[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.cursor-pointer > .w-full >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>805cc40e-a1cc-460e-ade8-e2e959b6e34f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://api.dicebear.com/7.x/avataaars/svg?seed=Felix</value>
      <webElementGuid>e283d8c4-ae7d-48d7-8dd3-15d3590950cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full aspect-square rounded-full bg-white shadow-sm</value>
      <webElementGuid>c71b0264-ac30-4942-8eab-c8213af871a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;max-w-5xl mx-auto p-6 space-y-8&quot;]/div[@class=&quot;grid grid-cols-1 md:grid-cols-3 gap-6&quot;]/div[@class=&quot;bg-card text-card-foreground gap-6 rounded-xl border py-6 shadow-sm md:col-span-2 min-h-[500px] flex flex-col&quot;]/div[@class=&quot;p-6&quot;]/div[@class=&quot;grid grid-cols-3 sm:grid-cols-4 gap-4&quot;]/div[@class=&quot;cursor-pointer relative rounded-xl p-1 border-2 transition-all hover:bg-slate-50 border-indigo-600 bg-indigo-50 ring-2 ring-indigo-200&quot;]/img[@class=&quot;w-full aspect-square rounded-full bg-white shadow-sm&quot;]</value>
      <webElementGuid>f3651c59-d36e-4961-96b7-4146be2a320b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[3]/div[2]/div[2]/div/div/img</value>
      <webElementGuid>d96065f1-4e2d-4b87-8604-61be3d54ce2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://api.dicebear.com/7.x/avataaars/svg?seed=Felix')])[2]</value>
      <webElementGuid>677bad44-22be-4043-8df5-ff96e25f2dd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/img</value>
      <webElementGuid>22af082c-3c1a-471e-ab15-2f11ea4900f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://api.dicebear.com/7.x/avataaars/svg?seed=Felix']</value>
      <webElementGuid>b2458405-4e79-462c-bb7e-5e835d398016</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
