<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>queenAvatarOwned</name>
   <tag></tag>
   <elementGuidId>cf0e237a-75cb-4b93-b63a-98381b0c7b4a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div[3]/div[2]/div[2]/div/div[7]/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>f9ee3ffb-89c0-43cf-bc6a-6f4d74483394</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://api.dicebear.com/7.x/avataaars/svg?seed=Queen</value>
      <webElementGuid>1d064330-49cb-43c9-821b-b25fa8613c6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full aspect-square rounded-full bg-white shadow-sm</value>
      <webElementGuid>d30435c6-adcd-4a66-a5f5-2a1fa75e6f7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;max-w-5xl mx-auto p-6 space-y-8 min-h-screen bg-slate-50/50&quot;]/div[@class=&quot;grid grid-cols-1 md:grid-cols-3 gap-6&quot;]/div[@class=&quot;text-card-foreground gap-6 rounded-xl border py-6 md:col-span-2 min-h-[500px] flex flex-col border-slate-200 shadow-sm bg-white&quot;]/div[@class=&quot;p-6&quot;]/div[@class=&quot;grid grid-cols-3 sm:grid-cols-4 gap-4&quot;]/div[@class=&quot;cursor-pointer relative rounded-xl p-1 border-2 transition-all hover:bg-slate-50 hover:-translate-y-1 border-indigo-600 bg-indigo-50 ring-2 ring-indigo-200&quot;]/img[@class=&quot;w-full aspect-square rounded-full bg-white shadow-sm&quot;]</value>
      <webElementGuid>4389916b-c87e-464e-a97a-10bdefc5c683</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[3]/div[2]/div[2]/div/div[7]/img</value>
      <webElementGuid>e098a4b2-f3aa-43b9-b814-89b96e80cc00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://api.dicebear.com/7.x/avataaars/svg?seed=Queen')])[2]</value>
      <webElementGuid>e360e996-d5b4-48bd-90dc-ca003cb8193b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/img</value>
      <webElementGuid>55fb7a3b-b40e-46fa-9753-1bf007f6cb3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://api.dicebear.com/7.x/avataaars/svg?seed=Queen']</value>
      <webElementGuid>21540f54-5ebe-4480-aacd-2572ee9d9c83</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
