<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>faceUpTrump</name>
   <tag></tag>
   <elementGuidId>fc1b3796-3ac6-46fc-ad3c-d7d84972fedf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div[3]/div/div/div[2]/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.trump-field.flex.flex-col.items-center > div.relative > div.card.w-28.h-40.shadow-lg > img.card-img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>div >> internal:has-text=/^33 cardsTrumpCPU$/ >> internal:attr=[alt=&quot;carta&quot;i] >> nth=1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>779b2efb-8feb-4752-a763-fb4250f1f738</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/decks/default/o1.png</value>
      <webElementGuid>0afd3c08-38ef-4656-a575-7c65edf556eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>carta</value>
      <webElementGuid>9ce8345d-64ba-4c70-a369-10533018c5a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>card-img</value>
      <webElementGuid>a5857baf-8535-4ddb-9e72-33ae20e40fcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>draggable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>af7bf12e-ad99-4196-a1bc-3988d9eeb984</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;game-board flex flex-col items-center justify-between min-h-screen bg-green-700 p-4 relative&quot;]/div[@class=&quot;table-row flex items-center justify-between w-full max-w-5xl mb-8&quot;]/div[@class=&quot;deck-area flex items-center&quot;]/div[@class=&quot;deck-and-trump flex items-end gap-6&quot;]/div[@class=&quot;trump-field flex flex-col items-center&quot;]/div[@class=&quot;relative&quot;]/div[@class=&quot;card w-28 h-40 shadow-lg&quot;]/img[@class=&quot;card-img&quot;]</value>
      <webElementGuid>88c5f66b-746b-45f4-868e-149f6e444e79</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[3]/div/div/div[2]/div/div/img</value>
      <webElementGuid>5f849d12-dd41-47de-82e2-09610ad87eea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='carta'])[4]</value>
      <webElementGuid>86084f19-816b-4aef-866a-9b2c7051f4e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[2]/div/div/img</value>
      <webElementGuid>03713fe7-95dc-4e3e-92bf-dcbcd10fe8e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/decks/default/o1.png' and @alt = 'carta']</value>
      <webElementGuid>01cc8a1a-0269-4809-b8fc-83a07b9f6d1c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
