<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>firstCardInHand</name>
   <tag></tag>
   <elementGuidId>2a021605-b423-4889-bd91-a5eda630e0e8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.card-container > div.card > img.card-img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//div[@id='app']/div/div[3]/div/div/div/img)[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.card-container > .card > .card-img >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>8b0e9a3d-02c3-4f4f-94b2-60d40beaec45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/src/assets/cards/c7.png</value>
      <webElementGuid>61d099b7-0eec-45ec-a174-fd882ce79429</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>carta</value>
      <webElementGuid>b71d3f3c-e7e6-47dd-b03b-438a155e9c67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>card-img</value>
      <webElementGuid>2365c36c-4e19-4fbc-8872-6dd8f21a100c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;game-board flex flex-col items-center justify-between min-h-screen bg-green-700 p-4&quot;]/div[@class=&quot;player-hand flex justify-center mb-8&quot;]/div[@class=&quot;player-hand w-28 h-40&quot;]/div[@class=&quot;card-container&quot;]/div[@class=&quot;card&quot;]/img[@class=&quot;card-img&quot;]</value>
      <webElementGuid>bc529fcb-fad2-4afe-bd47-fbcb9c54a112</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[3]/div/div/div/img</value>
      <webElementGuid>b447e6ea-2536-4616-a2cd-e491268415eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='carta'])[12]</value>
      <webElementGuid>c194abb5-c290-41ad-b3fa-3705bbe5c6eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/img</value>
      <webElementGuid>89863851-ef7c-4a85-8efb-57f88c810f0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/src/assets/cards/c7.png' and @alt = 'carta']</value>
      <webElementGuid>1048ff45-6122-40fe-b5c2-d827960bb0d5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
