<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>profileAvatar</name>
   <tag></tag>
   <elementGuidId>b4432cbd-b5c1-4729-b888-4eff62fdb4c5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='reka-dropdown-menu-trigger-v-5']/span[2]/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.aspect-square.size-full</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>70589bdf-cf2f-4277-8a75-7ab567516def</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>c3efc7df-56d4-4f04-b8b1-4e554236344d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://api.dicebear.com/7.x/avataaars/svg?seed=Orus</value>
      <webElementGuid>74ca154e-b6da-4dea-875a-dee376e6affa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-slot</name>
      <type>Main</type>
      <value>avatar-image</value>
      <webElementGuid>bdb322d6-9e6f-4718-b4a8-25f80e13b1b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>aspect-square size-full</value>
      <webElementGuid>798f91fb-7090-4f41-a1ad-e9122b862a09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;reka-dropdown-menu-trigger-v-5&quot;)/span[@class=&quot;relative flex size-8 shrink-0 overflow-hidden rounded-full cursor-pointer bg-slate-100 group-hover:ring-2 group-hover:ring-slate-200 transition&quot;]/img[@class=&quot;aspect-square size-full&quot;]</value>
      <webElementGuid>1fb77411-0413-4d8b-94db-ce50657696fc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='reka-dropdown-menu-trigger-v-5']/span[2]/img</value>
      <webElementGuid>c752292c-bcc9-4ca0-8283-fcacebe94d7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://api.dicebear.com/7.x/avataaars/svg?seed=Orus')]</value>
      <webElementGuid>9ff85002-5db6-4c6d-a076-293e0c46b70e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>2bdd716b-e622-4aa3-ba48-59e32405bc2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://api.dicebear.com/7.x/avataaars/svg?seed=Orus']</value>
      <webElementGuid>d13ed1f4-6032-4c11-abe3-d76a2891c796</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='reka-dropdown-menu-trigger-v-4']/span[2]/img</value>
      <webElementGuid>6b82da9b-922f-45e2-8d30-28f25646275f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
