<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_prevPage</name>
   <tag></tag>
   <elementGuidId>972e2f1c-f8d1-4233-87eb-a1a2af7b858f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.page-btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div[2]/div/div[2]/div[3]/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>80cb42b9-2ac7-476d-a581-c4641eb8a684</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>page-btn</value>
      <webElementGuid>28b8a568-3170-4859-8c58-25dbf0908b04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> « Prev </value>
      <webElementGuid>d37cc5c7-7a8f-4652-92d0-9ff3683cabaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;scoreboard-container&quot;]/div[2]/div[@class=&quot;global-wrapper&quot;]/div[@class=&quot;ranking-list-card&quot;]/div[@class=&quot;pagination-controls&quot;]/button[@class=&quot;page-btn&quot;]</value>
      <webElementGuid>aab5763b-3f4e-4cf2-8f30-56e440a6b167</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[2]/div/div[2]/div[3]/button</value>
      <webElementGuid>8dd9284c-e694-41df-aa8a-301555e6e88b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mickey459'])[1]/following::button[1]</value>
      <webElementGuid>41106730-dab6-40bd-bf58-cf8d680f8ecc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mickey42'])[1]/following::button[1]</value>
      <webElementGuid>b97ee479-d1b8-493a-b75c-e049b5ed0994</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Next »'])[1]/preceding::button[1]</value>
      <webElementGuid>8a0bea7c-238d-44f6-8253-2b6abc18eb6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='« Prev']/parent::*</value>
      <webElementGuid>019d4736-2df9-4cb8-9b77-37fe789207ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/button</value>
      <webElementGuid>c104dfee-a68b-4fd1-a5c4-5d09c0f7c9cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = ' « Prev ' or . = ' « Prev ')]</value>
      <webElementGuid>88304138-bdba-4cee-9a27-1eea35174794</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
