<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Capotes_stat-card highlight-gold</name>
   <tag></tag>
   <elementGuidId>081eaa80-009a-4fff-9572-d8562a9ada5e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.stat-card.highlight-gold</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div[2]/div/div[12]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>6a9c2fb0-08fa-47cd-be9c-28e66ed08892</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>stat-card highlight-gold</value>
      <webElementGuid>d2b3f2d6-671f-4934-9a66-51e5d2c2a53a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Bandeiras2</value>
      <webElementGuid>5409cffd-b344-4f47-9e9b-436a841209be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;scoreboard-container&quot;]/div[2]/div[@class=&quot;stats-grid&quot;]/div[@class=&quot;stat-card highlight-gold&quot;]</value>
      <webElementGuid>1c7a1e5c-70cc-48b9-988c-5be593061fd6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[2]/div/div[12]</value>
      <webElementGuid>2625811e-79cf-4ab0-8549-efa81f3d65b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Capotes'])[1]/following::div[1]</value>
      <webElementGuid>1b134f7e-179e-4541-8a80-5cc75bf0f2b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Riscas'])[1]/following::div[2]</value>
      <webElementGuid>338c0ba6-5ae9-493c-9415-0649a400099c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[12]</value>
      <webElementGuid>48fe937a-66a9-4571-857a-4494cd30f4ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Bandeiras2' or . = 'Bandeiras2')]</value>
      <webElementGuid>d37aafd0-955b-454f-8e9b-4ae88fd62283</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
