<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>matchCards</name>
   <tag></tag>
   <elementGuidId>d52eec44-ccd7-437a-8170-4231458dfb22</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div/div/div/h3/div/div[2]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.text-xl.font-bold.whitespace-nowrap</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;304 - 416&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>e8f914c1-5d7c-44de-9c17-5b482f008fbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-xl font-bold whitespace-nowrap</value>
      <webElementGuid>1d0ac8fe-43e5-4189-a80c-683abf82ff3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>304 - 416</value>
      <webElementGuid>c406a85a-cf63-4957-9b17-9c9982837426</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;min-h-screen bg-gradient-to-b from-emerald-10 to-emerald-100 flex flex-col font-sans select-none&quot;]/div[@class=&quot;flex flex-col justify-center items-center gap-5 mt-10 p-4&quot;]/div[@class=&quot;text-card-foreground flex flex-col gap-6 rounded-xl border py-6 shadow-sm w-full max-w-5xl bg-red-300&quot;]/div[@class=&quot;@container/card-header grid auto-rows-min grid-rows-[auto_auto] items-start gap-1.5 px-6 has-data-[slot=card-action]:grid-cols-[1fr_auto] [.border-b]:pb-6&quot;]/h3[@class=&quot;text-2xl font-bold&quot;]/div[@class=&quot;grid grid-cols-[1fr_auto_1fr] items-center w-full&quot;]/div[@class=&quot;flex flex-col items-center leading-tight&quot;]/span[@class=&quot;text-xl font-bold whitespace-nowrap&quot;]</value>
      <webElementGuid>932a5fc9-4586-4d98-9ebc-5a497bf9cb11</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div/div/h3/div/div[2]/span</value>
      <webElementGuid>caba78df-cb98-40c2-ac03-f3b5efc0be28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Game History'])[1]/following::span[2]</value>
      <webElementGuid>098cf62b-0476-48dc-958c-a99b84bcd0af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Player A'])[1]/following::span[3]</value>
      <webElementGuid>a754c74f-85eb-48f4-88af-fc3e8afb7a55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(2 - 4)'])[1]/preceding::span[1]</value>
      <webElementGuid>57f4f0d6-aaa1-4d2c-bf57-42f6d8c83b4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Player A'])[2]/preceding::span[2]</value>
      <webElementGuid>e726ce5f-568c-4409-9c7e-4d8e664b6993</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='304 - 416']/parent::*</value>
      <webElementGuid>6c94446e-d36c-461a-ab52-e5c167f59857</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/span</value>
      <webElementGuid>66f36a39-d0e6-42c4-9d0d-fbfade7b4186</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '304 - 416' or . = '304 - 416')]</value>
      <webElementGuid>76472c94-126c-4b5c-a7e7-55686635b96c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
